services:

  test:
    build:
      dockerfile: Dockerfile-test
    tty: true
    command: npm run test-code
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/home/node:rw,cached
      - /home/node/node_modules
      - /home/node/.npm

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /data/db
    ports:
      - "27020:27017/tcp"

  redis:
    image: redis:7
    volumes:
      - /data